/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.event.KeyEvent;
import DAO.*;
import Modelo.*;
import javax.swing.JOptionPane;
/**
 *
 * @author thermaltaque
 */
public class DetalleFactura extends javax.swing.JInternalFrame {

   CRUDproductos crudp = new CRUDproductos();
   Al_Producto pro = new Al_Producto();
    public DetalleFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomProFac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodProFac = new javax.swing.JTextField();
        txtPrecioFac = new javax.swing.JTextField();
        botAgreProFac = new javax.swing.JButton();
        txtCantidadFac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDetalle = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnRegisFac = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDNIFac = new javax.swing.JTextField();
        cbcEmpleadoFac = new javax.swing.JComboBox<>();
        TotalFac = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jdataFactura = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("REGISTRAR FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 400, 45));
        jPanel1.add(txtNomProFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Codigo Producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, -1, -1));

        txtCodProFac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodProFacKeyPressed(evt);
            }
        });
        jPanel1.add(txtCodProFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, 50));
        jPanel1.add(txtPrecioFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 120, 50));

        botAgreProFac.setText("Agregar Producto");
        botAgreProFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAgreProFacActionPerformed(evt);
            }
        });
        jPanel1.add(botAgreProFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 80, 140, 60));
        jPanel1.add(txtCantidadFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 100, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 1270, 180));

        TablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaDetalle);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 1270, 390));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fecha:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        btnRegisFac.setText("Registrar Factura");
        jPanel2.add(btnRegisFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 170, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Total:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Codigo Empleado:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));
        jPanel2.add(txtDNIFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 160, 50));

        jPanel2.add(cbcEmpleadoFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 180, 50));
        jPanel2.add(TotalFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 120, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Dni Cliente:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jdataFactura.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(jdataFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 170, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 1280, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodProFacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProFacKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER){
         if (!"".equals(txtCodProFac.getText())){
           String cod = txtCodProFac.getText();
             pro = crudp.BuscarProducto(cod);
             if(pro.getNombre_P()!= null){
                txtNomProFac.setText(""+pro.getNombre_P());
                txtPrecioFac.setText(""+pro.getPrecio());
                txtCantidadFac.requestFocus();
             } else{
                 txtNomProFac.setText("");
                txtPrecioFac.setText("");
             txtCodProFac.requestFocus();
             }
           
         }else {
           JOptionPane.showMessageDialog(null,"Ingrese el codigo del producto");
           txtCodProFac.setText("");
           txtCodProFac.requestFocus();
         }
      }
    }//GEN-LAST:event_txtCodProFacKeyPressed

    private void botAgreProFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAgreProFacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botAgreProFacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaDetalle;
    public javax.swing.JTextField TotalFac;
    public javax.swing.JButton botAgreProFac;
    public javax.swing.JButton btnRegisFac;
    public javax.swing.JComboBox<String> cbcEmpleadoFac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public com.toedter.calendar.JDateChooser jdataFactura;
    public javax.swing.JTextField txtCantidadFac;
    public javax.swing.JTextField txtCodProFac;
    public javax.swing.JTextField txtDNIFac;
    public javax.swing.JTextField txtNomProFac;
    public javax.swing.JTextField txtPrecioFac;
    // End of variables declaration//GEN-END:variables
}
