/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author thermaltaque
 */
public class Empleado extends javax.swing.JInternalFrame  {

    /**
     * Creates new form Empleado
     */
    public Empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtCodigoE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtNombreE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtApellidoE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtDireccionE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtTelefonoE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtEdadE = new javax.swing.JTextField();
        jspnDiasTrabajoE = new javax.swing.JSpinner();
        jbtnAgregarE = new javax.swing.JButton();
        jbtnModificarE = new javax.swing.JButton();
        jbtnConsultarE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtSueldoE = new javax.swing.JTextField();
        jbtnEliminarE1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblListaEmpleado = new javax.swing.JTable();
        jlbListaEmpleado = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("DNI Empleado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(jtxtCodigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jtxtNombreE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreEActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtNombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 200, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jtxtApellidoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtApellidoEActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtApellidoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 200, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Direccion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        jPanel1.add(jtxtDireccionE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 200, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Telefono:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jtxtTelefonoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelefonoEActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtTelefonoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 200, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Sueldo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 20));

        jtxtEdadE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEdadEActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtEdadE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 200, 40));

        jspnDiasTrabajoE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dias Trabajado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.add(jspnDiasTrabajoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 290, 70));

        jbtnAgregarE.setBackground(new java.awt.Color(0, 0, 0));
        jbtnAgregarE.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregarE.setText("Agregar");
        jPanel1.add(jbtnAgregarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 110, 40));

        jbtnModificarE.setBackground(new java.awt.Color(0, 0, 0));
        jbtnModificarE.setForeground(new java.awt.Color(255, 255, 255));
        jbtnModificarE.setText("Modificar");
        jbtnModificarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarEActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnModificarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 110, 40));

        jbtnConsultarE.setBackground(new java.awt.Color(0, 0, 0));
        jbtnConsultarE.setForeground(new java.awt.Color(255, 255, 255));
        jbtnConsultarE.setText("Consultar");
        jbtnConsultarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsultarEActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnConsultarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Edad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jtxtSueldoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSueldoEActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtSueldoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 200, 40));

        jbtnEliminarE1.setBackground(new java.awt.Color(0, 0, 0));
        jbtnEliminarE1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminarE1.setText("Eliminar");
        jbtnEliminarE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarE1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEliminarE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 710, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 760));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Lista de Empleados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 400, 40));

        jtblListaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblListaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblListaEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblListaEmpleado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 1010, 640));

        jlbListaEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbListaEmpleado.setText("Numero de Empleados:");
        getContentPane().add(jlbListaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 730, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtApellidoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtApellidoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtApellidoEActionPerformed

    private void jtxtEdadEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEdadEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEdadEActionPerformed

    private void jtxtTelefonoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelefonoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelefonoEActionPerformed

    private void jbtnConsultarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsultarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConsultarEActionPerformed

    private void jbtnModificarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnModificarEActionPerformed

    private void jtxtNombreEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreEActionPerformed

    private void jtxtSueldoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSueldoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSueldoEActionPerformed

    private void jtblListaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblListaEmpleadoMouseClicked
       
            int fila = jtblListaEmpleado.rowAtPoint(evt.getPoint());
       jtxtCodigoE.setText(jtblListaEmpleado.getValueAt(fila,1).toString());
       jtxtNombreE.setText(jtblListaEmpleado.getValueAt(fila,2).toString());
       jtxtApellidoE.setText(jtblListaEmpleado.getValueAt(fila,3).toString());
       jtxtDireccionE.setText(jtblListaEmpleado.getValueAt(fila,4).toString());
       jtxtTelefonoE.setText(jtblListaEmpleado.getValueAt(fila,5).toString());
       jtxtSueldoE.setText(jtblListaEmpleado.getValueAt(fila,6).toString());
       jtxtEdadE.setText(jtblListaEmpleado.getValueAt(fila,7).toString());
       jspnDiasTrabajoE.setValue(jtblListaEmpleado.getValueAt(fila,8));  
    }//GEN-LAST:event_jtblListaEmpleadoMouseClicked

    private void jbtnEliminarE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEliminarE1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Empleado().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnAgregarE;
    public javax.swing.JButton jbtnConsultarE;
    public javax.swing.JButton jbtnEliminarE1;
    public javax.swing.JButton jbtnModificarE;
    public javax.swing.JLabel jlbListaEmpleado;
    public javax.swing.JSpinner jspnDiasTrabajoE;
    public javax.swing.JTable jtblListaEmpleado;
    public javax.swing.JTextField jtxtApellidoE;
    public javax.swing.JTextField jtxtCodigoE;
    public javax.swing.JTextField jtxtDireccionE;
    public javax.swing.JTextField jtxtEdadE;
    public javax.swing.JTextField jtxtNombreE;
    public javax.swing.JTextField jtxtSueldoE;
    public javax.swing.JTextField jtxtTelefonoE;
    // End of variables declaration//GEN-END:variables
}
