/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import DAO.*;
import DAO.ConectarBD;
import Formatos.Mensajes;
import Modelo.Al_Producto;
import java.sql.SQLException;
import javax.swing.JTable;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author thermaltaque
 */
public class Facturas extends javax.swing.JInternalFrame  {

     CRUDfacturas crud = new CRUDfacturas();
    public Facturas() {
        initComponents();
        crud.MostrarCodFactura(jtblFacturasF,"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtCod_Factura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnConsultarF = new javax.swing.JButton();
        jtbnModificarF = new javax.swing.JButton();
        jbtnEliminarF = new javax.swing.JButton();
        jtxtTotalF = new javax.swing.JTextField();
        jtxtDNIF = new javax.swing.JTextField();
        jFechaFl = new com.toedter.calendar.JDateChooser();
        jtxtCodigo_Empleado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblFacturasF = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jfechaFConsultra = new com.toedter.calendar.JDateChooser();
        jConsultaFactura = new javax.swing.JTextField();
        jtxtCFacturas = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCod_Factura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.add(jtxtCod_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 190, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Codigo Factura:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("DNI Cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Empleado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Fecha:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jbtnConsultarF.setBackground(new java.awt.Color(0, 0, 0));
        jbtnConsultarF.setForeground(new java.awt.Color(255, 255, 255));
        jbtnConsultarF.setText("Consultar");
        jPanel1.add(jbtnConsultarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 170, 50));

        jtbnModificarF.setBackground(new java.awt.Color(0, 0, 0));
        jtbnModificarF.setForeground(new java.awt.Color(255, 255, 255));
        jtbnModificarF.setText("Modificar");
        jPanel1.add(jtbnModificarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 160, 50));

        jbtnEliminarF.setBackground(new java.awt.Color(0, 0, 0));
        jbtnEliminarF.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminarF.setText("Eliminar");
        jPanel1.add(jbtnEliminarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 720, 160, 50));
        jPanel1.add(jtxtTotalF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 200, 40));
        jPanel1.add(jtxtDNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 200, 40));

        jFechaFl.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jFechaFl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 210, 40));

        jPanel1.add(jtxtCodigo_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 230, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 800));

        jtblFacturasF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblFacturasF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblFacturasFMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblFacturasF);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 940, 530));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Registro de Facturas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));

        jfechaFConsultra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        getContentPane().add(jfechaFConsultra, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 340, 100));

        jConsultaFactura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese la factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jConsultaFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jConsultaFacturaKeyReleased(evt);
            }
        });
        getContentPane().add(jConsultaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 100, 260, 90));

        jtxtCFacturas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCFacturas.setText("Cantidad De Facturas:");
        getContentPane().add(jtxtCFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 770, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblFacturasFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblFacturasFMouseClicked
        try {
            int fila = jtblFacturasF.rowAtPoint(evt.getPoint());
            int fecha = jtblFacturasF.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)jtblFacturasF.getModel();
            jtxtCod_Factura.setText(jtblFacturasF.getValueAt(fila,1).toString());
            jtxtDNIF.setText(jtblFacturasF.getValueAt(fila,2).toString());
            jtxtCodigo_Empleado.setSelectedIndex(jtblFacturasF.getSelectedColumn());
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(fecha,4).toString());
            jFechaFl.setDate(date);
            jtxtTotalF.setText(jtblFacturasF.getValueAt(fila,5).toString());
        } catch (ParseException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jtblFacturasFMouseClicked

    private void jConsultaFacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jConsultaFacturaKeyReleased
      crud.MostrarCodFactura(jtblFacturasF,jConsultaFactura.getText());
    }//GEN-LAST:event_jConsultaFacturaKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Facturas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField jConsultaFactura;
    public com.toedter.calendar.JDateChooser jFechaFl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnConsultarF;
    public javax.swing.JButton jbtnEliminarF;
    public com.toedter.calendar.JDateChooser jfechaFConsultra;
    public javax.swing.JTable jtblFacturasF;
    public javax.swing.JButton jtbnModificarF;
    public javax.swing.JLabel jtxtCFacturas;
    public javax.swing.JTextField jtxtCod_Factura;
    public javax.swing.JComboBox<String> jtxtCodigo_Empleado;
    public javax.swing.JTextField jtxtDNIF;
    public javax.swing.JTextField jtxtTotalF;
    // End of variables declaration//GEN-END:variables
}
