/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author thermaltaque
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        jbtnVisualizarM = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        jbtnFacturaM = new javax.swing.JMenuItem();
        meRegistrarFactura = new javax.swing.JMenuItem();
        DetalleFactura = new javax.swing.JMenuItem();
        menu3 = new javax.swing.JMenu();
        jbtnReporteDiarioM = new javax.swing.JMenuItem();
        jbtnReporteSemanalM = new javax.swing.JMenuItem();
        jbtnReporteMensualM = new javax.swing.JMenuItem();
        menu4 = new javax.swing.JMenu();
        jbtnProductosM = new javax.swing.JMenuItem();
        jbtnEmpleadosM = new javax.swing.JMenuItem();
        menu5 = new javax.swing.JMenu();
        jSalirM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        javax.swing.GroupLayout jescritorioLayout = new javax.swing.GroupLayout(jescritorio);
        jescritorio.setLayout(jescritorioLayout);
        jescritorioLayout.setHorizontalGroup(
            jescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1205, Short.MAX_VALUE)
        );
        jescritorioLayout.setVerticalGroup(
            jescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        menu1.setText("Productos");

        jbtnVisualizarM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jbtnVisualizarM.setText("Visualizar");
        jbtnVisualizarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVisualizarMActionPerformed(evt);
            }
        });
        menu1.add(jbtnVisualizarM);

        jMenuBar1.add(menu1);

        menu2.setText("Ventas");

        jbtnFacturaM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jbtnFacturaM.setText("Facturas");
        menu2.add(jbtnFacturaM);

        meRegistrarFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        meRegistrarFactura.setText("Registrar Factura");
        menu2.add(meRegistrarFactura);

        DetalleFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        DetalleFactura.setText("Detalle Factura");
        menu2.add(DetalleFactura);

        jMenuBar1.add(menu2);

        menu3.setText("Reportes");

        jbtnReporteDiarioM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jbtnReporteDiarioM.setText("Reporte Diario");
        jbtnReporteDiarioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReporteDiarioMActionPerformed(evt);
            }
        });
        menu3.add(jbtnReporteDiarioM);

        jbtnReporteSemanalM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jbtnReporteSemanalM.setText("Reporte Semanal");
        jbtnReporteSemanalM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReporteSemanalMActionPerformed(evt);
            }
        });
        menu3.add(jbtnReporteSemanalM);

        jbtnReporteMensualM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jbtnReporteMensualM.setText("Reporte Mensual");
        menu3.add(jbtnReporteMensualM);

        jMenuBar1.add(menu3);

        menu4.setText("Mantenimiento");

        jbtnProductosM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jbtnProductosM.setText("Productos");
        menu4.add(jbtnProductosM);

        jbtnEmpleadosM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jbtnEmpleadosM.setText("Empleados");
        jbtnEmpleadosM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmpleadosMActionPerformed(evt);
            }
        });
        menu4.add(jbtnEmpleadosM);

        jMenuBar1.add(menu4);

        menu5.setText("Volver");

        jSalirM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jSalirM.setText("Salir");
        menu5.add(jSalirM);

        jMenuBar1.add(menu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jescritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnReporteDiarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReporteDiarioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnReporteDiarioMActionPerformed

    private void jbtnVisualizarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVisualizarMActionPerformed
        
           
    }//GEN-LAST:event_jbtnVisualizarMActionPerformed

    private void jbtnReporteSemanalMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReporteSemanalMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnReporteSemanalMActionPerformed

    private void jbtnEmpleadosMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmpleadosMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEmpleadosMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem DetalleFactura;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jSalirM;
    public javax.swing.JMenuItem jbtnEmpleadosM;
    public javax.swing.JMenuItem jbtnFacturaM;
    public javax.swing.JMenuItem jbtnProductosM;
    public javax.swing.JMenuItem jbtnReporteDiarioM;
    public javax.swing.JMenuItem jbtnReporteMensualM;
    public javax.swing.JMenuItem jbtnReporteSemanalM;
    public javax.swing.JMenuItem jbtnVisualizarM;
    public javax.swing.JDesktopPane jescritorio;
    public javax.swing.JMenuItem meRegistrarFactura;
    public javax.swing.JMenu menu1;
    public javax.swing.JMenu menu2;
    public javax.swing.JMenu menu3;
    public javax.swing.JMenu menu4;
    public javax.swing.JMenu menu5;
    // End of variables declaration//GEN-END:variables
}
