/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author thermaltaque
 */
public class MenuEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form MenuEmpleado
     */
    public MenuEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        VisualizarE = new javax.swing.JMenuItem();
        FacturasE = new javax.swing.JMenu();
        buttonFacturasE = new javax.swing.JMenuItem();
        meRegistrarFactura = new javax.swing.JMenuItem();
        DetalleFactura = new javax.swing.JMenuItem();
        ReporteDiarioE = new javax.swing.JMenu();
        buttonReporteDiarioE = new javax.swing.JMenuItem();
        SalirE = new javax.swing.JMenu();
        jSalirE = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jescritorioLayout = new javax.swing.GroupLayout(jescritorio);
        jescritorio.setLayout(jescritorioLayout);
        jescritorioLayout.setHorizontalGroup(
            jescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        jescritorioLayout.setVerticalGroup(
            jescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jMenu1.setText("Productos");

        VisualizarE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        VisualizarE.setText("Visualizar");
        VisualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarEActionPerformed(evt);
            }
        });
        jMenu1.add(VisualizarE);

        jMenuBar1.add(jMenu1);

        FacturasE.setText("Ventas");

        buttonFacturasE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buttonFacturasE.setText("Facturas");
        FacturasE.add(buttonFacturasE);

        meRegistrarFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        meRegistrarFactura.setText("Registrar Factura");
        FacturasE.add(meRegistrarFactura);

        DetalleFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        DetalleFactura.setText("Detalle Factura");
        FacturasE.add(DetalleFactura);

        jMenuBar1.add(FacturasE);

        ReporteDiarioE.setText("Reporte");

        buttonReporteDiarioE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buttonReporteDiarioE.setText("Reporte Diario");
        buttonReporteDiarioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReporteDiarioEActionPerformed(evt);
            }
        });
        ReporteDiarioE.add(buttonReporteDiarioE);

        jMenuBar1.add(ReporteDiarioE);

        SalirE.setText("Volver");

        jSalirE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jSalirE.setText("Salir");
        jSalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirEActionPerformed(evt);
            }
        });
        SalirE.add(jSalirE);

        jMenuBar1.add(SalirE);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jescritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VisualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisualizarEActionPerformed

    private void buttonReporteDiarioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReporteDiarioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReporteDiarioEActionPerformed

    private void jSalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSalirEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem DetalleFactura;
    public javax.swing.JMenu FacturasE;
    public javax.swing.JMenu ReporteDiarioE;
    public javax.swing.JMenu SalirE;
    public javax.swing.JMenuItem VisualizarE;
    public javax.swing.JMenuItem buttonFacturasE;
    public javax.swing.JMenuItem buttonReporteDiarioE;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jSalirE;
    public javax.swing.JDesktopPane jescritorio;
    public javax.swing.JMenuItem meRegistrarFactura;
    // End of variables declaration//GEN-END:variables
}
