/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author thermaltaque
 */
public class Productos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        jtxtCodigoProducto = new javax.swing.JTextField();
        jtxtNombrePro = new javax.swing.JTextField();
        jtxtPrecioP = new javax.swing.JTextField();
        jbtnConsultarP = new javax.swing.JButton();
        jbtnEliminarP = new javax.swing.JButton();
        jbtnModificarP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCategoriaP = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcbcTamañoP = new javax.swing.JComboBox<>();
        jtxtStockP = new javax.swing.JComboBox<>();
        jbtnAgregarP1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblListaProductos = new javax.swing.JTable();
        jlblProductos = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 0, 63))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Codigo Producto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Precio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 20));

        Stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Stock.setText("Stock:");
        jPanel1.add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jtxtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 210, 40));
        jPanel1.add(jtxtNombrePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, 40));
        jPanel1.add(jtxtPrecioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 210, 50));

        jbtnConsultarP.setBackground(new java.awt.Color(0, 0, 0));
        jbtnConsultarP.setForeground(new java.awt.Color(255, 255, 255));
        jbtnConsultarP.setText("Consultar");
        jbtnConsultarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsultarPActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnConsultarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 130, 50));

        jbtnEliminarP.setBackground(new java.awt.Color(0, 0, 0));
        jbtnEliminarP.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminarP.setText("Eliminar");
        jbtnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarPActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEliminarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 130, 50));

        jbtnModificarP.setBackground(new java.awt.Color(0, 0, 0));
        jbtnModificarP.setForeground(new java.awt.Color(255, 255, 255));
        jbtnModificarP.setText("Modificar");
        jPanel1.add(jbtnModificarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 130, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Categoria:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jPanel1.add(jCategoriaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 220, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tamaño:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jPanel1.add(jcbcTamañoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 220, 50));

        jPanel1.add(jtxtStockP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 220, 50));

        jbtnAgregarP1.setBackground(new java.awt.Color(0, 0, 0));
        jbtnAgregarP1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregarP1.setText("Agregar");
        jbtnAgregarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarP1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAgregarP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 130, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 630));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Lista de Productos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 370, 30));

        jtblListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblListaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblListaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblListaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 920, 590));

        jlblProductos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblProductos.setText("Cantidad de Productos:");
        getContentPane().add(jlblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoProductoActionPerformed

    private void jbtnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEliminarPActionPerformed

    private void jbtnConsultarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsultarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnConsultarPActionPerformed

    private void jbtnAgregarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarP1ActionPerformed

    private void jtblListaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblListaProductosMouseClicked
        int fila = jtblListaProductos.rowAtPoint(evt.getPoint());
       jtxtCodigoProducto.setText(jtblListaProductos.getValueAt(fila,1).toString());
       jtxtNombrePro.setText(jtblListaProductos.getValueAt(fila,2).toString());
       jtxtPrecioP.setText(jtblListaProductos.getValueAt(fila,3).toString());
        
    }//GEN-LAST:event_jtblListaProductosMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Productos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Stock;
    public javax.swing.JComboBox<String> jCategoriaP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnAgregarP1;
    public javax.swing.JButton jbtnConsultarP;
    public javax.swing.JButton jbtnEliminarP;
    public javax.swing.JButton jbtnModificarP;
    public javax.swing.JComboBox<String> jcbcTamañoP;
    public javax.swing.JLabel jlblProductos;
    public javax.swing.JTable jtblListaProductos;
    public javax.swing.JTextField jtxtCodigoProducto;
    public javax.swing.JTextField jtxtNombrePro;
    public javax.swing.JTextField jtxtPrecioP;
    public javax.swing.JComboBox<String> jtxtStockP;
    // End of variables declaration//GEN-END:variables
}
