/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import DAO.*;
import DAO.ConectarBD;
/**
 *
 * @author thermaltaque
 */
public class Reporte_semanal extends javax.swing.JInternalFrame {

   CRUDreporteSemanal crud = new CRUDreporteSemanal();
    public Reporte_semanal() {
        initComponents();
        crud.MostrarNreporteEnTabla(jtblRsemanal, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbuscarRS = new javax.swing.JButton();
        RestauraraRS = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jfechafinal = new javax.swing.JTextField();
        jfechainicial1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRsemanal = new javax.swing.JTable();
        jbCDP = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Reporte Semanal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Filtro por Nº reporte:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Filtro por fecha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 160, -1));

        jbuscarRS.setBackground(new java.awt.Color(0, 0, 0));
        jbuscarRS.setForeground(new java.awt.Color(255, 255, 255));
        jbuscarRS.setText("Buscar");
        jPanel1.add(jbuscarRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 160, 60));

        RestauraraRS.setBackground(new java.awt.Color(0, 0, 0));
        RestauraraRS.setForeground(new java.awt.Color(255, 255, 255));
        RestauraraRS.setText("Restaurar");
        jPanel1.add(RestauraraRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 150, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pizzas.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 100, -1));

        jfechafinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jfechafinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jfechafinalKeyReleased(evt);
            }
        });
        jPanel1.add(jfechafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 190, 60));

        jfechainicial1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jfechainicial1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jfechainicial1KeyReleased(evt);
            }
        });
        jPanel1.add(jfechainicial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 170, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 440, 720));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Reporte Semanal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 460, -1));

        jtblRsemanal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblRsemanal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 910, 590));

        jbCDP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCDP.setText("Cantidad De Reportes:");
        getContentPane().add(jbCDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 700, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfechainicial1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jfechainicial1KeyReleased
        crud.MostrarNreporteEnTabla(jtblRsemanal, jfechainicial1.getText());
    }//GEN-LAST:event_jfechainicial1KeyReleased

    private void jfechafinalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jfechafinalKeyReleased
       crud.MostrarfechaEnTabla(jtblRsemanal, jfechafinal.getText());
    }//GEN-LAST:event_jfechafinalKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton RestauraraRS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jbCDP;
    public javax.swing.JButton jbuscarRS;
    public javax.swing.JTextField jfechafinal;
    public javax.swing.JTextField jfechainicial1;
    public javax.swing.JTable jtblRsemanal;
    // End of variables declaration//GEN-END:variables
}
