/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author thermaltaque
 */
public class Reporte_Diario extends javax.swing.JInternalFrame  {

    /**
     * Creates new form Reporte_Diario
     */
    public Reporte_Diario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtFechaR = new com.toedter.calendar.JDateChooser();
        jtxtDineroInicialRD = new javax.swing.JTextField();
        jtxtPlatosVendidos = new javax.swing.JTextField();
        jbtnConsultarRD = new javax.swing.JButton();
        jbtnEliminarRD = new javax.swing.JButton();
        jbtnModificarRD = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxtTotalRD = new javax.swing.JTextField();
        jtxtEmpleadoR = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jtxNReporte = new javax.swing.JTextField();
        jbtnRegistrarRD1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtPizzaVendida = new javax.swing.JTextField();
        jtxtPastasVendida = new javax.swing.JTextField();
        jtxtBebidasVendidas = new javax.swing.JTextField();
        jtxtPiqueoVendido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblReporteDiaRB = new javax.swing.JTable();
        jblCRD = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reporte Diario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pizzas vendidas:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nº de Reporte:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Platos C. vendidos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Dinero Inicial:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Fecha:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        jtxtFechaR.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jtxtFechaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 200, 40));
        jPanel1.add(jtxtDineroInicialRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 190, 40));

        jtxtPlatosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPlatosVendidosActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtPlatosVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 140, 40));

        jbtnConsultarRD.setBackground(new java.awt.Color(0, 0, 0));
        jbtnConsultarRD.setForeground(new java.awt.Color(255, 255, 255));
        jbtnConsultarRD.setText("Consultar");
        jPanel1.add(jbtnConsultarRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 140, 50));

        jbtnEliminarRD.setBackground(new java.awt.Color(0, 0, 0));
        jbtnEliminarRD.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminarRD.setText("Eliminar");
        jbtnEliminarRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarRDActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEliminarRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 670, 130, 50));

        jbtnModificarRD.setBackground(new java.awt.Color(0, 0, 0));
        jbtnModificarRD.setForeground(new java.awt.Color(255, 255, 255));
        jbtnModificarRD.setText("Modificar");
        jPanel1.add(jbtnModificarRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 750, 130, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Total de Dinero:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));
        jPanel1.add(jtxtTotalRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 190, 40));

        jtxtEmpleadoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmpleadoRActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtEmpleadoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 190, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Codigo Empleado:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel1.add(jtxNReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 140, 50));

        jbtnRegistrarRD1.setBackground(new java.awt.Color(0, 0, 0));
        jbtnRegistrarRD1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarRD1.setText("Registrar");
        jPanel1.add(jbtnRegistrarRD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 140, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("bebidas vendidas:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Pastas vendidas:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Piqueos vendidos:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jtxtPizzaVendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPizzaVendidaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtPizzaVendida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 140, 40));

        jtxtPastasVendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPastasVendidaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtPastasVendida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 140, 40));

        jtxtBebidasVendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBebidasVendidasActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtBebidasVendidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 140, 40));

        jtxtPiqueoVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPiqueoVendidoActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtPiqueoVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 390, 820));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 2, 2));
        jLabel6.setText("Reporte del dia");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jtblReporteDiaRB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblReporteDiaRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblReporteDiaRBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblReporteDiaRB);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 950, 640));

        jblCRD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblCRD.setText("Cantidad De Reporte Diario:");
        getContentPane().add(jblCRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 760, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEliminarRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarRDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEliminarRDActionPerformed

    private void jtblReporteDiaRBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblReporteDiaRBMouseClicked
         int fila = jtblReporteDiaRB.rowAtPoint(evt.getPoint());
       jtxNReporte.setText(jtblReporteDiaRB.getValueAt(fila,1).toString());
       jtxtPizzaVendida.setText(jtblReporteDiaRB.getValueAt(fila,3).toString());
       jtxtPastasVendida.setText(jtblReporteDiaRB.getValueAt(fila,4).toString());
       jtxtBebidasVendidas.setText(jtblReporteDiaRB.getValueAt(fila,5).toString());
       jtxtPiqueoVendido.setText(jtblReporteDiaRB.getValueAt(fila,6).toString());
       jtxtPlatosVendidos.setText(jtblReporteDiaRB.getValueAt(fila,7).toString());
       jtxtDineroInicialRD.setText(jtblReporteDiaRB.getValueAt(fila,9).toString());
        jtxtTotalRD.setText(jtblReporteDiaRB.getValueAt(fila,10).toString());  
    }//GEN-LAST:event_jtblReporteDiaRBMouseClicked

    private void jtxtEmpleadoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmpleadoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmpleadoRActionPerformed

    private void jtxtPlatosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPlatosVendidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPlatosVendidosActionPerformed

    private void jtxtPizzaVendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPizzaVendidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPizzaVendidaActionPerformed

    private void jtxtPastasVendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPastasVendidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPastasVendidaActionPerformed

    private void jtxtBebidasVendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBebidasVendidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBebidasVendidasActionPerformed

    private void jtxtPiqueoVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPiqueoVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPiqueoVendidoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Reporte_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Reporte_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Reporte_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Reporte_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Reporte_Diario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jblCRD;
    public javax.swing.JButton jbtnConsultarRD;
    public javax.swing.JButton jbtnEliminarRD;
    public javax.swing.JButton jbtnModificarRD;
    public javax.swing.JButton jbtnRegistrarRD1;
    public javax.swing.JTable jtblReporteDiaRB;
    public javax.swing.JTextField jtxNReporte;
    public javax.swing.JTextField jtxtBebidasVendidas;
    public javax.swing.JTextField jtxtDineroInicialRD;
    public javax.swing.JComboBox<String> jtxtEmpleadoR;
    public com.toedter.calendar.JDateChooser jtxtFechaR;
    public javax.swing.JTextField jtxtPastasVendida;
    public javax.swing.JTextField jtxtPiqueoVendido;
    public javax.swing.JTextField jtxtPizzaVendida;
    public javax.swing.JTextField jtxtPlatosVendidos;
    public javax.swing.JTextField jtxtTotalRD;
    // End of variables declaration//GEN-END:variables
}
