/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import DAO.*;
import DAO.ConectarBD;
import Formatos.Mensajes;
import Modelo.Al_Producto;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author thermaltaque
 */
public class Visualizar extends javax.swing.JInternalFrame  {

    ConectarBD cc = new ConectarBD();
    CRUDvisualizar crudv = new CRUDvisualizar();
    private  TableRowSorter filtro;
    public Visualizar() {
        initComponents();
        crudv.MostrarProductoEnTabla(jtblVisualizar,"");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbcCategoriaV = new javax.swing.JComboBox<>();
        jcbcStockV = new javax.swing.JComboBox<>();
        JCDP = new javax.swing.JLabel();
        jFiltroTamano = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcbcProductoV = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtnRestaurar = new javax.swing.JButton();
        jbtnFCategoria = new javax.swing.JButton();
        jbtnFProducto = new javax.swing.JButton();
        jbtnFStock = new javax.swing.JButton();
        jbtnFiltrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblVisualizar = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jcbcCategoriaV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.add(jcbcCategoriaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 240, 80));

        jcbcStockV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.add(jcbcStockV, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 250, 80));

        JCDP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JCDP.setForeground(new java.awt.Color(255, 255, 255));
        JCDP.setText("Cantidad De Productos:");
        jPanel1.add(JCDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, -1, -1));

        jFiltroTamano.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tamaño", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.add(jFiltroTamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 100, 200, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filtro Por Producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jcbcProductoV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbcProductoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbcProductoVActionPerformed(evt);
            }
        });
        jcbcProductoV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcbcProductoVKeyReleased(evt);
            }
        });
        jPanel1.add(jcbcProductoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 210, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 200));

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnRestaurar.setText("Restaurar");
        jPanel3.add(jbtnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 180, 40));

        jbtnFCategoria.setText("Filtrar Categoria");
        jPanel3.add(jbtnFCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 150, 40));

        jbtnFProducto.setText("Filtrar Tamaño");
        jPanel3.add(jbtnFProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 140, 40));

        jbtnFStock.setText("Filtrar Stock");
        jbtnFStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFStockActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnFStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 140, 40));

        jbtnFiltrar.setText("Filtrar");
        jPanel3.add(jbtnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 50, 120, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1380, 150));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblVisualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblVisualizar);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 1100, 360));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1380, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnFStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFStockActionPerformed
      
    }//GEN-LAST:event_jbtnFStockActionPerformed

    private void jcbcProductoVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbcProductoVKeyReleased
      crudv.MostrarProductoEnTabla(jtblVisualizar,jcbcProductoV.getText());
    }//GEN-LAST:event_jcbcProductoVKeyReleased

    private void jcbcProductoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbcProductoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbcProductoVActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Visualizar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JCDP;
    public javax.swing.JComboBox<String> jFiltroTamano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnFCategoria;
    public javax.swing.JButton jbtnFProducto;
    public javax.swing.JButton jbtnFStock;
    public javax.swing.JButton jbtnFiltrar;
    public javax.swing.JButton jbtnRestaurar;
    public javax.swing.JComboBox<String> jcbcCategoriaV;
    public javax.swing.JTextField jcbcProductoV;
    public javax.swing.JComboBox<String> jcbcStockV;
    public javax.swing.JTable jtblVisualizar;
    // End of variables declaration//GEN-END:variables
}
